---
name: eliud_pkg_wizards
description: eliud_pkg_wizards is a package to provide wizards. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_wizards
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_main: ^1.3.0
  eliud_core_model: ^1.3.0
  eliud_pkg_etc: ^1.3.0
  eliud_pkg_etc_model: ^1.3.0
  eliud_pkg_fundamentals: ^1.3.0
  eliud_pkg_fundamentals_model: ^1.3.0
  eliud_pkg_membership: ^1.3.0
  eliud_pkg_pay: ^1.3.0
  eliud_pkg_shop: ^1.3.0
  eliud_pkg_text: ^1.3.0
  eliud_pkg_workflow: ^1.3.0
  eliud_pkg_workflow_model: ^1.3.0
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_wizards/assets/about.png
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.pdf
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.jpg
  - packages/eliud_pkg_wizards/assets/blocked.png
platforms:
  android: null
  ios: null
  web: null
dev_dependencies:
  lints: ^5.0.0
