---
name: eliud_pkg_wizards
description: eliud_pkg_wizards is a package to provide wizards. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_wizards
version: 1.1.5+5
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core: ^1.1.5+7
  eliud_pkg_text: ^1.1.5+6
  eliud_pkg_fundamentals: ^1.1.5+6
  eliud_pkg_etc: ^1.1.5+8
  eliud_pkg_shop: ^1.1.5+9
  eliud_pkg_membership: ^1.1.5+5
  eliud_pkg_workflow: ^1.1.5+5
  eliud_pkg_pay: ^1.1.5+5
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_wizards/assets/about.png
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.pdf
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.jpg
  - packages/eliud_pkg_wizards/assets/blocked.png
platforms:
  android: null
  ios: null
  web: null
dev_dependencies:
  lints: ^3.0.0
