---
name: eliud_pkg_wizards
description: eliud_pkg_wizards is a package to provide wizards. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_wizards
version: 1.1.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_core_model:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_core_model
  eliud_pkg_membership:                                                                              # ANDROID IOS             WEB
    path: ../eliud_pkg_membership
  eliud_pkg_workflow:                                                                                # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow
  eliud_pkg_fundamentals_model:                                                                      # ANDROID IOS             WEB
    path: ../eliud_pkg_fundamentals_model
  eliud_pkg_text:                                                                                    # ANDROID IOS             WEB
    path: ../eliud_pkg_text
  eliud_pkg_pay:                                                                                     # ANDROID IOS             WEB
    path: ../eliud_pkg_pay
  eliud_pkg_shop:                                                                                    # ANDROID IOS             WEB
    path: ../eliud_pkg_shop

  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_wizards/assets/about.png
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.pdf
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.jpg
  - packages/eliud_pkg_wizards/assets/blocked.png
platforms:
  android: null
  ios: null
  web: null
dev_dependencies:
  lints: ^3.0.0
