---
name: eliud_pkg_wizards
description: This package can be included in your eliud app (https://eliud.io) and
  can be used to extend your app with wizards. Wizards allow to add functionalities
  quickly.
homepage: https://github.com/eliudio/eliud_core
repository: https://github.com/eliudio/eliud_pkg_wizards
version: 1.1.3
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  eliud_core: ^1.1.3
  eliud_pkg_text: ^1.1.3
  eliud_pkg_fundamentals: ^1.1.3
  eliud_pkg_etc: ^1.1.3
  eliud_pkg_shop: ^1.1.3
  eliud_pkg_membership: ^1.1.3
  eliud_pkg_workflow: ^1.1.3
  eliud_pkg_pay: ^1.1.3
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_wizards/assets/about.png
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.pdf
  - packages/eliud_pkg_wizards/assets/new_app/legal/policies.jpg
  - packages/eliud_pkg_wizards/assets/blocked.png
platforms:
  android: null
  ios: null
  web: null
dev_dependencies:
  lints: ^3.0.0
