name: eliud_pkg_wizards
description: A package with wizards for pages

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_text:
    path: ../eliud_pkg_text

  eliud_pkg_fundamentals:
    path: ../eliud_pkg_fundamentals

  eliud_pkg_etc:
    path: ../eliud_pkg_etc

  eliud_pkg_shop:
    path: ../eliud_pkg_shop

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_wizards/assets/about.png
    - packages/eliud_pkg_wizards/assets/new_app/legal/policies.pdf
    - packages/eliud_pkg_wizards/assets/new_app/legal/policies.jpg
    - packages/eliud_pkg_wizards/assets/blocked.png
